"""create job match table

Revision ID: 2984ffd86094
Revises: c41ec28e6dbd
Create Date: 2026-06-30 23:48:25.595070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2984ffd86094'
down_revision: Union[str, Sequence[str], None] = 'c41ec28e6dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=False),
    sa.Column('missing_keywords', sa.Text(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('weaknesses', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_matches')
    # ### end Alembic commands ###
